name: deploy
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "18.20.5"
      - name: "Install"
        run: |
          npm i
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "."
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_PORT: ${{ secrets.SSH_PORT }}
            REMOTE_USER: ${{ secrets.SSH_USERNAME }}
            TARGET: "~/Websites/personal-web"
            EXCLUDE: "/dist/, /node_modules/"
